language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"   
  - "3.7"
  - "3.8"
  - "3.8-dev"  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest

