apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
  selector:
    app: kafka
   

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
  - name: zookeeper
    port: 2181
    targetPort: 2181

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper
        imagePullPolicy: Always
        ports:
        - containerPort: 2181
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
       
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_PORT
          value: "9092"         
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-service"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 0.0.0.0/0.0.0.0:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: "addAction:1:1,apigateway:1:1,DataRetrieval:1:1,postanalysis:1:1"
